"""Emit frontend JSON catalogs from services.shared.dataset_registry.

Do not hand-edit the generated files. Regenerate with:

    python scripts/generate_frontend_registry.py
"""

from __future__ import annotations

import json
from pathlib import Path

from services.agent.caveats import CAVEAT_TEXT
from services.shared.dataset_registry import DATASETS

ROOT = Path(__file__).resolve().parents[1]
CAVEATS_PATH = ROOT / "shared" / "dataset_caveats.json"
DATASETS_PATH = ROOT / "shared" / "datasets.json"
GENERATED_NOTE = (
    "Generated by scripts/generate_frontend_registry.py. Do not hand-edit. "
    "Regenerate with: python scripts/generate_frontend_registry.py"
)


def caveat_catalog() -> dict[str, str]:
    """Static caveat strings only. Dynamic ids (e.g. calfire_missingness) are skipped."""
    catalog: dict[str, str] = {"$generated": GENERATED_NOTE}
    for entry in DATASETS.values():
        for cid in entry.caveat_ids:
            if cid in CAVEAT_TEXT and cid not in catalog:
                catalog[cid] = CAVEAT_TEXT[cid]
    return catalog


def dataset_catalog() -> dict[str, object]:
    datasets = []
    for entry in DATASETS.values():
        style = None
        if entry.style:
            style = {
                "color": entry.style.get("color"),
                "geometry_type": entry.style.get("geometry_type"),
                "label": entry.style.get("label"),
            }
        datasets.append(
            {
                "key": entry.key,
                "aliases": list(entry.aliases),
                "viz_key": entry.viz_key,
                "style": style,
                "allowed_filters": list(entry.allowed_filters),
            }
        )
    return {"$generated": GENERATED_NOTE, "datasets": datasets}


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> None:
    write_json(CAVEATS_PATH, caveat_catalog())
    write_json(DATASETS_PATH, dataset_catalog())


if __name__ == "__main__":
    main()
